name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Lynsz
          BRANCH_NAME: main
          UTC_OFFSET: -3
          THEME: tokyonight
